// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry/output.proto

package registry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Artifact struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Artifact) Reset()         { *m = Artifact{} }
func (m *Artifact) String() string { return proto.CompactTextString(m) }
func (*Artifact) ProtoMessage()    {}
func (*Artifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_5885729ef5a158fa, []int{0}
}

func (m *Artifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artifact.Unmarshal(m, b)
}
func (m *Artifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artifact.Marshal(b, m, deterministic)
}
func (m *Artifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artifact.Merge(m, src)
}
func (m *Artifact) XXX_Size() int {
	return xxx_messageInfo_Artifact.Size(m)
}
func (m *Artifact) XXX_DiscardUnknown() {
	xxx_messageInfo_Artifact.DiscardUnknown(m)
}

var xxx_messageInfo_Artifact proto.InternalMessageInfo

func (m *Artifact) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type AccessInfo struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessInfo) Reset()         { *m = AccessInfo{} }
func (m *AccessInfo) String() string { return proto.CompactTextString(m) }
func (*AccessInfo) ProtoMessage()    {}
func (*AccessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5885729ef5a158fa, []int{1}
}

func (m *AccessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessInfo.Unmarshal(m, b)
}
func (m *AccessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessInfo.Marshal(b, m, deterministic)
}
func (m *AccessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessInfo.Merge(m, src)
}
func (m *AccessInfo) XXX_Size() int {
	return xxx_messageInfo_AccessInfo.Size(m)
}
func (m *AccessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccessInfo proto.InternalMessageInfo

func (m *AccessInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *AccessInfo) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*Artifact)(nil), "registry.Artifact")
	proto.RegisterType((*AccessInfo)(nil), "registry.AccessInfo")
}

func init() {
	proto.RegisterFile("registry/output.proto", fileDescriptor_5885729ef5a158fa)
}

var fileDescriptor_5885729ef5a158fa = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0x6e, 0x83, 0x30,
	0x14, 0x45, 0x45, 0xab, 0x22, 0xea, 0xa9, 0xb2, 0xda, 0x8a, 0xb1, 0x62, 0xea, 0x02, 0x1e, 0x92,
	0x1f, 0x20, 0x5b, 0x96, 0x28, 0xca, 0x98, 0x25, 0x32, 0x8e, 0x31, 0x4f, 0x32, 0x7e, 0x96, 0xfd,
	0xac, 0x84, 0xbf, 0x8f, 0x02, 0x61, 0xbb, 0xe7, 0xe8, 0x0e, 0x87, 0xfd, 0x04, 0x6d, 0x20, 0x52,
	0x98, 0x04, 0x26, 0xf2, 0x89, 0x1a, 0x1f, 0x90, 0x90, 0x17, 0xab, 0xae, 0x2a, 0x56, 0xb4, 0x81,
	0xa0, 0x97, 0x8a, 0xf8, 0x2f, 0xcb, 0x23, 0xa6, 0xa0, 0x74, 0x99, 0xfd, 0x65, 0xff, 0x9f, 0xa7,
	0x17, 0x55, 0x5b, 0xc6, 0x5a, 0xa5, 0x74, 0x8c, 0x7b, 0xd7, 0x23, 0xff, 0x66, 0x1f, 0x30, 0x4a,
	0xb3, 0x9e, 0x16, 0xe0, 0x5f, 0xec, 0x9d, 0xa4, 0x29, 0xdf, 0x66, 0xf7, 0x9c, 0xbb, 0xe3, 0xf9,
	0x60, 0x80, 0x86, 0xd4, 0x35, 0x0a, 0x47, 0x31, 0xc8, 0x38, 0x80, 0xc2, 0xe0, 0xc5, 0x4d, 0x4e,
	0x1e, 0xc1, 0x51, 0xed, 0x6d, 0x32, 0xe0, 0x6a, 0x7d, 0x97, 0xa3, 0xb7, 0x3a, 0x8a, 0x85, 0xa3,
	0x30, 0xd8, 0x25, 0xb0, 0x57, 0x1d, 0x2e, 0x3d, 0x38, 0x69, 0xc5, 0xda, 0xda, 0xe5, 0x73, 0xfc,
	0xe6, 0x11, 0x00, 0x00, 0xff, 0xff, 0x92, 0x43, 0x85, 0x77, 0xd5, 0x00, 0x00, 0x00,
}
